In [493]:
# Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Inladen data:
1. Bovemij Dataset Portefeuille ontwikkelingen
2. CBS Auto verkopen
3. CBS Consumentenprijs index - verzekeringen ivm vervoer
4. CBS Consumentenprijs index - nieuwe auto's
5. CBS Consumentenprijs index - tweedehands auto's
6. CBS Consumentenprijs index - onderhoud en reparatie privevoertuigen
7. CBS Consumentenprijs index - brandstoffen en smeermiddelen

In [494]:
# Mapping van maandnamen naar maandnummers
# Deze mapping is nodig om de maandnamen in de CBS dataset om te zetten naar maandnummers, zodat we een correcte Datetime variabele kunnen maken.
maanden_dict = {
    'januari': '01', 'februari': '02', 'maart': '03', 'april': '04',
    'mei': '05', 'juni': '06', 'juli': '07', 'augustus': '08',
    'september': '09', 'oktober': '10', 'november': '11', 'december': '12'
}

Hieronder ga ik de dataset van Bovemij Portefeuille ontwikkelingen inladen

In [514]:
# Laden dataset Bovemij
df = pd.read_csv('../../data/raw/export_insurance_portfolio_data_forecasting_2000_2025.csv')

# Filter de data vanaf Jaarmaand 201501
df = df[df['Jaar_Maand'] >= 201501].reset_index(drop=True)

In [515]:
df.head()

,Jaar_Maand,Product,Label_Naam,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,...,Jaarpremie_voor_Prolongatie,Jaarpremie_na_Prolongatie,Mutaties,Jaarpremie_voor_Mutatie,Jaarpremie_na_Mutatie,Gemiddelde_Jaarpremie_Beginstand,Gemiddelde_Jaarpremie_Eindstand,Jaarpremie_Prolongatie,Gemiddelde_Jaarpremie_voor_Prolongatie,Gemiddelde_Jaarpremie_na_Prolongatie
0,201507,Auto Particulier,BCS Polis,50,29585.43,106,59337.54,56,28886.31,0,...,0.0,0.0,38,20242.19,21107.99,591.708600,559.788113,0.0,0.0,0.0
1,201508,Auto Particulier,BCS Polis,106,59337.54,168,91685.32,65,32911.85,1,...,0.0,0.0,46,21866.59,22007.44,559.788113,545.745952,0.0,0.0,0.0
2,201509,Auto Particulier,BCS Polis,168,91685.32,216,111434.76,54,23342.33,6,...,0.0,0.0,26,12065.70,13365.58,545.745952,515.901666,0.0,0.0,0.0
3,201510,Auto Particulier,BCS Polis,216,111434.76,265,133615.83,57,26433.61,6,...,0.0,0.0,45,23305.39,23313.57,515.901666,504.210679,0.0,0.0,0.0
4,201511,Auto Particulier,BCS Polis,265,133615.83,309,157925.46,49,26034.01,5,...,0.0,0.0,27,14114.42,14585.22,504.210679,511.085631,0.0,0.0,0.0

In [497]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2740 entries, 0 to 2739
Data columns (total 22 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Jaar_Maand                              2740 non-null   int64
 1   Product                                 2740 non-null   str
 2   Label_Naam                              2740 non-null   str
 3   Beginstand                              2740 non-null   int64
 4   Jaarpremie_Beginstand                   2740 non-null   float64
 5   Eindstand                               2740 non-null   int64
 6   Jaarpremie_Eindstand                    2740 non-null   float64
 7   NewBusiness                             2740 non-null   int64
 8   Jaarpremie_NewBusiness                  2740 non-null   float64
 9   Royementen                              2740 non-null   int64
 10  Geroyeerde_Jaarpremie                   2740 non-null   float64
 11  Prolongaties                            2740 non-null   int64
 12  Jaarpremie_voor_Prolongatie             2740 non-null   float64
 13  Jaarpremie_na_Prolongatie               2740 non-null   float64
 14  Mutaties                                2740 non-null   int64
 15  Jaarpremie_voor_Mutatie                 2740 non-null   float64
 16  Jaarpremie_na_Mutatie                   2740 non-null   float64
 17  Gemiddelde_Jaarpremie_Beginstand        2740 non-null   float64
 18  Gemiddelde_Jaarpremie_Eindstand         2740 non-null   float64
 19  Jaarpremie_Prolongatie                  2740 non-null   float64
 20  Gemiddelde_Jaarpremie_voor_Prolongatie  2740 non-null   float64
 21  Gemiddelde_Jaarpremie_na_Prolongatie    2740 non-null   float64
dtypes: float64(13), int64(7), str(2)
memory usage: 471.1 KB

In [498]:
df.describe()

,Jaar_Maand,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,Geroyeerde_Jaarpremie,Prolongaties,Jaarpremie_voor_Prolongatie,Jaarpremie_na_Prolongatie,Mutaties,Jaarpremie_voor_Mutatie,Jaarpremie_na_Mutatie,Gemiddelde_Jaarpremie_Beginstand,Gemiddelde_Jaarpremie_Eindstand,Jaarpremie_Prolongatie,Gemiddelde_Jaarpremie_voor_Prolongatie,Gemiddelde_Jaarpremie_na_Prolongatie
count,2740.000000,2740.000000,2.740000e+03,2740.000000,2.740000e+03,2740.000000,2.740000e+03,2740.000000,2740.000000,2740.000000,2.740000e+03,2.740000e+03,2740.000000,2.740000e+03,2.740000e+03,2740.000000,2740.000000,2740.000000,2740.000000,2740.000000
mean,202039.039781,6826.163139,3.677893e+06,6839.275547,3.701973e+06,105.539416,6.440573e+04,87.625547,49243.148161,486.267153,2.552805e+05,2.657935e+05,231.141971,1.377235e+05,1.384262e+05,605.037081,607.125256,10513.005755,548.284637,570.661996
std,308.057642,11641.759073,5.892633e+06,11652.997024,5.929001e+06,182.244834,1.061114e+05,157.641993,82886.580072,854.452964,4.216142e+05,4.415216e+05,1304.638809,7.989257e+05,7.991780e+05,152.337657,152.942193,28375.876814,220.977481,236.606350
min,201501.000000,1.000000,0.000000e+00,1.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,-28797.420000,0.000000,0.000000
25%,201803.000000,965.000000,5.812225e+05,984.500000,5.860705e+05,14.000000,9.478450e+03,9.000000,5921.937500,39.000000,2.367580e+04,2.444274e+04,25.000000,1.755026e+04,1.732017e+04,500.146201,502.044422,0.000000,471.400277,480.702486
50%,202012.000000,2788.500000,1.686578e+06,2792.500000,1.693925e+06,45.000000,2.883770e+04,37.000000,22547.570000,194.000000,1.128133e+05,1.173521e+05,69.000000,4.435019e+04,4.485909e+04,575.033573,576.742800,1636.100000,551.110844,567.527538
75%,202307.000000,7488.500000,4.254677e+06,7491.250000,4.267128e+06,116.250000,7.357099e+04,91.250000,49955.435000,554.250000,3.074643e+05,3.159048e+05,188.000000,1.064427e+05,1.071464e+05,676.719341,679.676242,9310.052500,642.801833,675.226993
max,202512.000000,60512.000000,3.931488e+07,60512.000000,3.955505e+07,3180.000000,1.598273e+06,1326.000000,678281.680000,6543.000000,3.515939e+06,3.856362e+06,59937.000000,3.538899e+07,3.539776e+07,1206.315553,1218.299338,340422.340000,1407.300000,1558.930000

Inladen dataset CBS aantal autoverkopen en mergen met Bovemij dataset

In [499]:
# Laden dataset CBS autoverkopen totaal per maand
df_cbs_autoverkopen = pd.read_csv('../../data/external/Verkochte_wegvoertuigen_09032026_090156.csv', sep=';')

In [500]:
df_cbs_autoverkopen.head()

,Wegvoertuigen,Brandstofsoort voertuig,Perioden,Totaal verkochte wegvoertuigen (aantal)
0,Personenauto,Totaal,2007 januari,311829
1,Personenauto,Totaal,2007 februari,268567
2,Personenauto,Totaal,2007 maart,299452
3,Personenauto,Totaal,2007 april,254358
4,Personenauto,Totaal,2007 mei,274026

In [501]:
# Data cleaning en transformatie van de CBS dataset

# 1. Verwijder het sterretje (*) van voorlopige cijfers en spaties
df_cbs_autoverkopen['Perioden'] = df_cbs_autoverkopen['Perioden'].str.replace('*', '', regex=False).str.strip()

# 2. Splits '2021 januari' in twee losse kolommen: '2021' en 'januari'
df_cbs_autoverkopen[['Jaar', 'Maand_Naam']] = df_cbs_autoverkopen['Perioden'].str.split(' ', expand=True)

# 3. Koppel het maandnummer eraan en maak een correcte Datetime variabele (YYYY-MM-01)
df_cbs_autoverkopen['Maand_Num'] = df_cbs_autoverkopen['Maand_Naam'].map(maanden_dict)
df_cbs_autoverkopen['Datum'] = pd.to_datetime(df_cbs_autoverkopen['Jaar'] + '-' + df_cbs_autoverkopen['Maand_Num'] + '-01')

# 4. We plakken Jaar en Maand_Num aan elkaar en maken er een integer van voor de merge
df_cbs_autoverkopen['Jaar_Maand'] = (df_cbs_autoverkopen['Jaar'] + df_cbs_autoverkopen['Maand_Num']).astype(int)

In [502]:
df_cbs_autoverkopen.head()

,Wegvoertuigen,Brandstofsoort voertuig,Perioden,Totaal verkochte wegvoertuigen (aantal),Jaar,Maand_Naam,Maand_Num,Datum,Jaar_Maand
0,Personenauto,Totaal,2007 januari,311829,2007,januari,01,2007-01-01,200701
1,Personenauto,Totaal,2007 februari,268567,2007,februari,02,2007-02-01,200702
2,Personenauto,Totaal,2007 maart,299452,2007,maart,03,2007-03-01,200703
3,Personenauto,Totaal,2007 april,254358,2007,april,04,2007-04-01,200704
4,Personenauto,Totaal,2007 mei,274026,2007,mei,05,2007-05-01,200705

In [503]:
# Filter de data vanaf Jaarmaand 201501
df_cbs_autoverkopen = df_cbs_autoverkopen[df_cbs_autoverkopen['Jaar_Maand'] >= 201501].reset_index(drop=True)

In [504]:
# Get unique values for Product and Label_Naam
unique_voertuigen = df_cbs_autoverkopen['Wegvoertuigen'].unique()
unique_brandstof = df_cbs_autoverkopen['Brandstofsoort voertuig'].unique()

# Count unique values
num_voertuigen = len(unique_voertuigen)
num_brandstof = len(unique_brandstof)

print(f"Unique Vehicles ({num_voertuigen}):")
print(unique_voertuigen)
print(f"\nUnique Fuel Types ({num_brandstof}):")
print(unique_brandstof)

Unique Vehicles (1):
<StringArray>
['Personenauto']
Length: 1, dtype: str

Unique Fuel Types (1):
<StringArray>
['Totaal']
Length: 1, dtype: str

In [505]:
df_cbs_autoverkopen.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 9 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Wegvoertuigen                            132 non-null    str
 1   Brandstofsoort voertuig                  132 non-null    str
 2   Perioden                                 132 non-null    str
 3   Totaal verkochte wegvoertuigen (aantal)  132 non-null    int64
 4   Jaar                                     132 non-null    str
 5   Maand_Naam                               132 non-null    str
 6   Maand_Num                                132 non-null    str
 7   Datum                                    132 non-null    datetime64[us]
 8   Jaar_Maand                               132 non-null    int64
dtypes: datetime64[us](1), int64(2), str(6)
memory usage: 9.4 KB

In [506]:
df_cbs_autoverkopen.describe()

,Totaal verkochte wegvoertuigen (aantal),Datum,Jaar_Maand
count,132.000000,132,132.000000
mean,268861.750000,2020-06-16 02:10:54.545454,202006.500000
min,201158.000000,2015-01-01 00:00:00,201501.000000
25%,255578.250000,2017-09-23 12:00:00,201709.750000
50%,268572.000000,2020-06-16 00:00:00,202006.500000
75%,283265.000000,2023-03-08 18:00:00,202303.250000
max,312471.000000,2025-12-01 00:00:00,202512.000000
std,20852.386709,NaN,317.451361

In [510]:
# We plakken de CBS data naast de Bovemij data. 

# 1. Voorbereiden van de CBS data
cbs_col_name = 'Totaal verkochte wegvoertuigen (aantal)'

# We maken een kopie en zorgen dat 'Jaar_Maand' beschikbaar is als kolom
# (Ik ga er vanuit dat df_cbs_autoverkopen de kolom 'Jaar_Maand' al heeft, 
# anders moet je de 'Perioden' kolom eerst omzetten zoals we eerder bespraken)
cbs_subset = df_cbs_autoverkopen[['Jaar_Maand', cbs_col_name]].copy()
cbs_subset = cbs_subset.rename(columns={cbs_col_name: 'CBS_Autoverkopen_Totaal'})

# 2. Mergen op de kolom 'Jaar_Maand'
# We gebruiken 'left' join om alle rijen van je Bovemij data (df) te behouden
df_merged_1 = pd.merge(df, cbs_subset, on='Jaar_Maand', how='left')

In [513]:
df_merged_1.head(24)

,Jaar_Maand,Product,Label_Naam,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,...,Jaarpremie_na_Prolongatie,Mutaties,Jaarpremie_voor_Mutatie,Jaarpremie_na_Mutatie,Gemiddelde_Jaarpremie_Beginstand,Gemiddelde_Jaarpremie_Eindstand,Jaarpremie_Prolongatie,Gemiddelde_Jaarpremie_voor_Prolongatie,Gemiddelde_Jaarpremie_na_Prolongatie,CBS_Autoverkopen_Totaal
0,201507,Auto Particulier,BCS Polis,50,29585.43,106,59337.54,56,28886.31,0,...,0.00,38,20242.19,21107.99,591.708600,559.788113,0.00,0.000000,0.000000,260815
1,201508,Auto Particulier,BCS Polis,106,59337.54,168,91685.32,65,32911.85,1,...,0.00,46,21866.59,22007.44,559.788113,545.745952,0.00,0.000000,0.000000,232190
2,201509,Auto Particulier,BCS Polis,168,91685.32,216,111434.76,54,23342.33,6,...,0.00,26,12065.70,13365.58,545.745952,515.901666,0.00,0.000000,0.000000,255645
3,201510,Auto Particulier,BCS Polis,216,111434.76,265,133615.83,57,26433.61,6,...,0.00,45,23305.39,23313.57,515.901666,504.210679,0.00,0.000000,0.000000,271074
4,201511,Auto Particulier,BCS Polis,265,133615.83,309,157925.46,49,26034.01,5,...,0.00,27,14114.42,14585.22,504.210679,511.085631,0.00,0.000000,0.000000,255282
5,201512,Auto Particulier,BCS Polis,309,157925.46,362,189921.27,55,29052.72,2,...,0.00,39,20897.45,24309.15,511.085631,524.644392,0.00,0.000000,0.000000,294494
6,201601,Auto Particulier,BCS Polis,362,189921.27,414,213983.45,55,24711.91,4,...,0.00,31,14000.11,14485.19,524.644392,516.868236,0.00,0.000000,0.000000,277579
7,201602,Auto Particulier,BCS Polis,414,213983.45,461,238785.32,53,26840.31,6,...,0.00,36,18862.39,19810.94,516.868236,517.972494,0.00,0.000000,0.000000,262034
8,201603,Auto Particulier,BCS Polis,461,238785.32,515,266500.13,60,31453.63,7,...,0.00,35,19659.15,20001.37,517.972494,517.475980,0.00,0.000000,0.000000,278227
9,201604,Auto Particulier,BCS Polis,515,266500.13,565,295008.22,56,30534.90,6,...,0.00,32,15753.59,17039.40,517.475980,522.138442,0.00,0.000000,0.000000,264313
10,201605,Auto Particulier,BCS Polis,565,295008.22,750,382485.99,191,88796.88,5,...,0.00,55,28014.75,29021.35,522.138442,509.981320,0.00,0.000000,0.000000,253759
11,201606,Auto Particulier,BCS Polis,750,382485.99,908,455768.36,173,78043.58,14,...,19844.16,75,36208.41,40985.25,509.981320,501.947533,-644.53,539.176052,522.214736,293318
12,201607,Auto Particulier,BCS Polis,908,455768.36,1064,524304.10,168,76141.62,12,...,23779.40,68,31617.55,30538.65,501.947533,492.767011,-389.68,514.235744,505.944680,264924
13,201608,Auto Particulier,BCS Polis,1064,524304.10,1231,598383.89,177,79634.60,13,...,26765.37,58,32738.32,32376.86,492.767011,486.095767,1116.49,493.247692,514.718653,239804
14,201609,Auto Particulier,BCS Polis,1231,598383.89,1374,660796.73,162,70031.30,18,...,20769.53,53,24035.43,24435.12,486.095767,480.929206,-203.60,446.236808,441.904893,257549
15,201610,Auto Particulier,BCS Polis,1374,660796.73,1533,729309.48,170,75488.96,11,...,22193.88,47,24381.46,23365.09,480.929206,475.740039,-436.25,491.959347,482.475652,264286
16,201611,Auto Particulier,BCS Polis,1533,729309.48,1706,810416.56,200,91920.31,26,...,22456.14,52,24360.99,25530.11,475.740039,475.039015,1166.56,545.886666,575.798461,260395
17,201612,Auto Particulier,BCS Polis,1706,810416.56,1848,870270.90,166,70229.67,22,...,25656.95,53,25287.24,27208.00,475.039015,470.925811,-231.29,562.787826,557.759782,260253
18,201701,Auto Particulier,BCS Polis,1848,870270.90,2009,944062.02,183,81019.62,20,...,19160.48,61,27995.71,29046.87,470.925811,469.916386,-595.24,493.893000,479.012000,293648
19,201702,Auto Particulier,BCS Polis,2009,944062.02,2159,1012387.72,179,83893.58,28,...,17550.74,46,23069.20,23728.26,469.916386,468.915108,-537.15,502.441388,487.520555,258559
20,201703,Auto Particulier,BCS Polis,2159,1012387.72,2324,1084842.81,195,86750.71,30,...,25731.75,69,34398.12,35226.83,468.915108,466.799832,-1499.95,523.686538,494.841346,290407
21,201704,Auto Particulier,BCS Polis,2324,1084842.81,2465,1141443.87,167,69499.48,26,...,21666.44,57,24254.68,26266.75,466.799832,463.060393,-257.43,562.150512,555.549743,247092
22,201705,Auto Particulier,BCS Polis,2465,1141443.87,2466,1141996.05,33,17148.00,28,...,70461.49,52,27737.16,25859.67,463.060393,463.096532,-1526.32,470.508562,460.532614,280324
23,201706,Auto Particulier,BCS Polis,2466,1141996.05,2461,1142746.70,35,19797.48,38,...,84954.79,56,27250.76,26905.09,463.096532,464.342421,3140.24,472.916473,491.068150,289854

In [512]:
df_merged_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 2740 entries, 0 to 2739
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Jaar_Maand                              2740 non-null   int64
 1   Product                                 2740 non-null   str
 2   Label_Naam                              2740 non-null   str
 3   Beginstand                              2740 non-null   int64
 4   Jaarpremie_Beginstand                   2740 non-null   float64
 5   Eindstand                               2740 non-null   int64
 6   Jaarpremie_Eindstand                    2740 non-null   float64
 7   NewBusiness                             2740 non-null   int64
 8   Jaarpremie_NewBusiness                  2740 non-null   float64
 9   Royementen                              2740 non-null   int64
 10  Geroyeerde_Jaarpremie                   2740 non-null   float64
 11  Prolongaties                            2740 non-null   int64
 12  Jaarpremie_voor_Prolongatie             2740 non-null   float64
 13  Jaarpremie_na_Prolongatie               2740 non-null   float64
 14  Mutaties                                2740 non-null   int64
 15  Jaarpremie_voor_Mutatie                 2740 non-null   float64
 16  Jaarpremie_na_Mutatie                   2740 non-null   float64
 17  Gemiddelde_Jaarpremie_Beginstand        2740 non-null   float64
 18  Gemiddelde_Jaarpremie_Eindstand         2740 non-null   float64
 19  Jaarpremie_Prolongatie                  2740 non-null   float64
 20  Gemiddelde_Jaarpremie_voor_Prolongatie  2740 non-null   float64
 21  Gemiddelde_Jaarpremie_na_Prolongatie    2740 non-null   float64
 22  CBS_Autoverkopen_Totaal                 2740 non-null   int64
dtypes: float64(13), int64(8), str(2)
memory usage: 492.5 KB

Inladen CBS CPI Verzekeringen ivm Vervoer dataset inladen en mergen met Bovemij dataset.

In [435]:
# Laden dataset CBS 
df_cbs_cpi_verzekeringen = pd.read_csv('../../data/external/CPI__prijsindex_2015_100_09032026_104238_125400_verzekeringen_ivm_vervoer.csv', sep=';')


# Data cleaning en transformatie van de CBS dataset
# 1. Verwijder het sterretje (*) van voorlopige cijfers en spaties
df_cbs_cpi_verzekeringen['Perioden'] = df_cbs_cpi_verzekeringen['Perioden'].str.replace('*', '', regex=False).str.strip()

# 2. Splits '2021 januari' in twee losse kolommen: '2021' en 'januari'
df_cbs_cpi_verzekeringen[['Jaar', 'Maand_Naam']] = df_cbs_cpi_verzekeringen['Perioden'].str.split(' ', expand=True)

# 3. Koppel het maandnummer eraan en maak een correcte Datetime variabele (YYYY-MM-01)
df_cbs_cpi_verzekeringen['Maand_Num'] = df_cbs_cpi_verzekeringen['Maand_Naam'].map(maanden_dict)
df_cbs_cpi_verzekeringen['Datum'] = pd.to_datetime(df_cbs_cpi_verzekeringen['Jaar'] + '-' + df_cbs_cpi_verzekeringen['Maand_Num'] + '-01')


# Filter de data vanaf Datum 2015-01-01 en reset de index voor een correcte joining later
df_cbs_cpi_verzekeringen = df_cbs_cpi_verzekeringen[df_cbs_cpi_verzekeringen['Datum'] >= '2015-01-01'].reset_index(drop=True)

In [436]:
df_cbs_cpi_verzekeringen.head()

,Bestedingscategorieën,Perioden,CPI (2015 = 100),Jaarmutatie CPI (%),Jaar,Maand_Naam,Maand_Num,Datum
0,125400 Verzekeringen i.v.m. vervoer,2015 januari,99.66,3.8,2015,januari,01,2015-01-01
1,125400 Verzekeringen i.v.m. vervoer,2015 februari,99.68,3.9,2015,februari,02,2015-02-01
2,125400 Verzekeringen i.v.m. vervoer,2015 maart,99.76,3.9,2015,maart,03,2015-03-01
3,125400 Verzekeringen i.v.m. vervoer,2015 april,99.79,3.8,2015,april,04,2015-04-01
4,125400 Verzekeringen i.v.m. vervoer,2015 mei,99.79,3.7,2015,mei,05,2015-05-01

In [437]:
df_cbs_cpi_verzekeringen.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bestedingscategorieën  132 non-null    str
 1   Perioden               132 non-null    str
 2   CPI (2015 = 100)       132 non-null    float64
 3   Jaarmutatie CPI (%)    132 non-null    float64
 4   Jaar                   132 non-null    str
 5   Maand_Naam             132 non-null    str
 6   Maand_Num              132 non-null    str
 7   Datum                  132 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 8.4 KB

In [438]:
df_cbs_cpi_verzekeringen.describe()

       CPI (2015 = 100)  Jaarmutatie CPI (%)                       Datum
count        132.000000           132.000000                         132
mean         119.338939             4.186364  2020-06-16 02:10:54.545454
min           99.660000            -7.600000         2015-01-01 00:00:00
25%          109.237500             1.875000         2017-09-23 12:00:00
50%          117.605000             3.800000         2020-06-16 00:00:00
75%          123.420000             6.850000         2023-03-08 18:00:00
max          156.140000            19.800000         2025-12-01 00:00:00
std           14.355464             5.413085                         NaN

In [439]:
# 1. Definieer de exacte namen die nu in je CBS dataframe staan
col_names = ['CPI (2015 = 100)', 'Jaarmutatie CPI (%)']

# 2. Selecteer deze kolommen
cbs_series = df_cbs_cpi_verzekeringen[col_names].copy()

# 3. Hernoem de kolommen handmatig naar namen met underscores
cbs_series.columns = ['CPI_Verzekeringen_Vervoer', 'Jaarmutatie_CPI_Verzekeringen_Vervoer']

# 4. Voeg ze samen met de Bovemij data
df_merged_2 = df_merged_1.join(cbs_series, how='inner')
df_merged_2.index.freq = 'MS'

In [440]:
df_merged_2.head()

,Jaar_Maand,Product,Label_Naam,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,...,Jaarpremie_voor_Mutatie,Jaarpremie_na_Mutatie,Gemiddelde_Jaarpremie_Beginstand,Gemiddelde_Jaarpremie_Eindstand,Jaarpremie_Prolongatie,Gemiddelde_Jaarpremie_voor_Prolongatie,Gemiddelde_Jaarpremie_na_Prolongatie,CBS_Autoverkopen_Totaal,CPI_Verzekeringen_Vervoer,Jaarmutatie_CPI_Verzekeringen_Vervoer
0,201507,Auto Particulier,BCS Polis,50,29585.43,106,59337.54,56,28886.31,0,...,20242.19,21107.99,591.708600,559.788113,0.0,0.0,0.0,284629,99.66,3.8
1,201508,Auto Particulier,BCS Polis,106,59337.54,168,91685.32,65,32911.85,1,...,21866.59,22007.44,559.788113,545.745952,0.0,0.0,0.0,243121,99.68,3.9
2,201509,Auto Particulier,BCS Polis,168,91685.32,216,111434.76,54,23342.33,6,...,12065.70,13365.58,545.745952,515.901666,0.0,0.0,0.0,257217,99.76,3.9
3,201510,Auto Particulier,BCS Polis,216,111434.76,265,133615.83,57,26433.61,6,...,23305.39,23313.57,515.901666,504.210679,0.0,0.0,0.0,247228,99.79,3.8
4,201511,Auto Particulier,BCS Polis,265,133615.83,309,157925.46,49,26034.01,5,...,14114.42,14585.22,504.210679,511.085631,0.0,0.0,0.0,244140,99.79,3.7

In [441]:
df_merged_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 25 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Jaar_Maand                              132 non-null    int64
 1   Product                                 132 non-null    str
 2   Label_Naam                              132 non-null    str
 3   Beginstand                              132 non-null    int64
 4   Jaarpremie_Beginstand                   132 non-null    float64
 5   Eindstand                               132 non-null    int64
 6   Jaarpremie_Eindstand                    132 non-null    float64
 7   NewBusiness                             132 non-null    int64
 8   Jaarpremie_NewBusiness                  132 non-null    float64
 9   Royementen                              132 non-null    int64
 10  Geroyeerde_Jaarpremie                   132 non-null    float64
 11  Prolongaties                            132 non-null    int64
 12  Jaarpremie_voor_Prolongatie             132 non-null    float64
 13  Jaarpremie_na_Prolongatie               132 non-null    float64
 14  Mutaties                                132 non-null    int64
 15  Jaarpremie_voor_Mutatie                 132 non-null    float64
 16  Jaarpremie_na_Mutatie                   132 non-null    float64
 17  Gemiddelde_Jaarpremie_Beginstand        132 non-null    float64
 18  Gemiddelde_Jaarpremie_Eindstand         132 non-null    float64
 19  Jaarpremie_Prolongatie                  132 non-null    float64
 20  Gemiddelde_Jaarpremie_voor_Prolongatie  132 non-null    float64
 21  Gemiddelde_Jaarpremie_na_Prolongatie    132 non-null    float64
 22  CBS_Autoverkopen_Totaal                 132 non-null    int64
 23  CPI_Verzekeringen_Vervoer               132 non-null    float64
 24  Jaarmutatie_CPI_Verzekeringen_Vervoer   132 non-null    float64
dtypes: float64(15), int64(8), str(2)
memory usage: 25.9 KB

Inladen CBS CPI Nieuwe Auto's dataset inladen en mergen met Bovemij dataset.

In [442]:
# Laden dataset CBS 
df_cbs_cpi_nieuwe_autos = pd.read_csv('../../data/external/CPI__prijsindex_2015_100_09032026_104511_071110_nieuwe_autos.csv', sep=';')


# Data cleaning en transformatie van de CBS dataset
# 1. Verwijder het sterretje (*) van voorlopige cijfers en spaties
df_cbs_cpi_nieuwe_autos['Perioden'] = df_cbs_cpi_nieuwe_autos['Perioden'].str.replace('*', '', regex=False).str.strip()

# 2. Splits '2021 januari' in twee losse kolommen: '2021' en 'januari'
df_cbs_cpi_nieuwe_autos[['Jaar', 'Maand_Naam']] = df_cbs_cpi_nieuwe_autos['Perioden'].str.split(' ', expand=True)

# 3. Koppel het maandnummer eraan en maak een correcte Datetime variabele (YYYY-MM-01)
df_cbs_cpi_nieuwe_autos['Maand_Num'] = df_cbs_cpi_nieuwe_autos['Maand_Naam'].map(maanden_dict)
df_cbs_cpi_nieuwe_autos['Datum'] = pd.to_datetime(df_cbs_cpi_nieuwe_autos['Jaar'] + '-' + df_cbs_cpi_nieuwe_autos['Maand_Num'] + '-01')


# Filter de data vanaf Datum 2015-01-01 en reset de index voor een correcte joining later
df_cbs_cpi_nieuwe_autos = df_cbs_cpi_nieuwe_autos[df_cbs_cpi_nieuwe_autos['Datum'] >= '2015-01-01'].reset_index(drop=True)

In [443]:
df_cbs_cpi_nieuwe_autos.head()

,Bestedingscategorieën,Perioden,CPI (2015 = 100),Jaarmutatie CPI (%),Jaar,Maand_Naam,Maand_Num,Datum
0,071110 Nieuwe auto's,2015 januari,100.16,2.7,2015,januari,01,2015-01-01
1,071110 Nieuwe auto's,2015 februari,100.03,2.4,2015,februari,02,2015-02-01
2,071110 Nieuwe auto's,2015 maart,100.05,2.7,2015,maart,03,2015-03-01
3,071110 Nieuwe auto's,2015 april,99.63,2.6,2015,april,04,2015-04-01
4,071110 Nieuwe auto's,2015 mei,99.52,2.5,2015,mei,05,2015-05-01

In [444]:
df_cbs_cpi_nieuwe_autos.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bestedingscategorieën  132 non-null    str
 1   Perioden               132 non-null    str
 2   CPI (2015 = 100)       132 non-null    float64
 3   Jaarmutatie CPI (%)    132 non-null    float64
 4   Jaar                   132 non-null    str
 5   Maand_Naam             132 non-null    str
 6   Maand_Num              132 non-null    str
 7   Datum                  132 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 8.4 KB

In [445]:
df_cbs_cpi_nieuwe_autos.describe()

       CPI (2015 = 100)  Jaarmutatie CPI (%)                       Datum
count        132.000000           132.000000                         132
mean         117.827576             3.331818  2020-06-16 02:10:54.545454
min           99.520000             1.200000         2015-01-01 00:00:00
25%          104.840000             2.000000         2017-09-23 12:00:00
50%          114.715000             3.000000         2020-06-16 00:00:00
75%          133.350000             3.900000         2023-03-08 18:00:00
max          139.310000             8.400000         2025-12-01 00:00:00
std           13.645054             1.692657                         NaN

In [446]:
# 1. Definieer de exacte namen die nu in je CBS dataframe staan
col_names = ['CPI (2015 = 100)', 'Jaarmutatie CPI (%)']

# 2. Selecteer deze kolommen
cbs_series = df_cbs_cpi_nieuwe_autos[col_names].copy()

# 3. Hernoem de kolommen handmatig naar namen met underscores
cbs_series.columns = ['CPI_Nieuwe_Autos', 'Jaarmutatie_CPI_Nieuwe_Autos']

# 4. Voeg ze samen met de Bovemij data
df_merged_3 = df_merged_2.join(cbs_series, how='inner')
df_merged_3.index.freq = 'MS'

In [447]:
df_merged_3.head()

,Jaar_Maand,Product,Label_Naam,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,...,Gemiddelde_Jaarpremie_Beginstand,Gemiddelde_Jaarpremie_Eindstand,Jaarpremie_Prolongatie,Gemiddelde_Jaarpremie_voor_Prolongatie,Gemiddelde_Jaarpremie_na_Prolongatie,CBS_Autoverkopen_Totaal,CPI_Verzekeringen_Vervoer,Jaarmutatie_CPI_Verzekeringen_Vervoer,CPI_Nieuwe_Autos,Jaarmutatie_CPI_Nieuwe_Autos
0,201507,Auto Particulier,BCS Polis,50,29585.43,106,59337.54,56,28886.31,0,...,591.708600,559.788113,0.0,0.0,0.0,284629,99.66,3.8,100.16,2.7
1,201508,Auto Particulier,BCS Polis,106,59337.54,168,91685.32,65,32911.85,1,...,559.788113,545.745952,0.0,0.0,0.0,243121,99.68,3.9,100.03,2.4
2,201509,Auto Particulier,BCS Polis,168,91685.32,216,111434.76,54,23342.33,6,...,545.745952,515.901666,0.0,0.0,0.0,257217,99.76,3.9,100.05,2.7
3,201510,Auto Particulier,BCS Polis,216,111434.76,265,133615.83,57,26433.61,6,...,515.901666,504.210679,0.0,0.0,0.0,247228,99.79,3.8,99.63,2.6
4,201511,Auto Particulier,BCS Polis,265,133615.83,309,157925.46,49,26034.01,5,...,504.210679,511.085631,0.0,0.0,0.0,244140,99.79,3.7,99.52,2.5

In [448]:
df_merged_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 27 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Jaar_Maand                              132 non-null    int64
 1   Product                                 132 non-null    str
 2   Label_Naam                              132 non-null    str
 3   Beginstand                              132 non-null    int64
 4   Jaarpremie_Beginstand                   132 non-null    float64
 5   Eindstand                               132 non-null    int64
 6   Jaarpremie_Eindstand                    132 non-null    float64
 7   NewBusiness                             132 non-null    int64
 8   Jaarpremie_NewBusiness                  132 non-null    float64
 9   Royementen                              132 non-null    int64
 10  Geroyeerde_Jaarpremie                   132 non-null    float64
 11  Prolongaties                            132 non-null    int64
 12  Jaarpremie_voor_Prolongatie             132 non-null    float64
 13  Jaarpremie_na_Prolongatie               132 non-null    float64
 14  Mutaties                                132 non-null    int64
 15  Jaarpremie_voor_Mutatie                 132 non-null    float64
 16  Jaarpremie_na_Mutatie                   132 non-null    float64
 17  Gemiddelde_Jaarpremie_Beginstand        132 non-null    float64
 18  Gemiddelde_Jaarpremie_Eindstand         132 non-null    float64
 19  Jaarpremie_Prolongatie                  132 non-null    float64
 20  Gemiddelde_Jaarpremie_voor_Prolongatie  132 non-null    float64
 21  Gemiddelde_Jaarpremie_na_Prolongatie    132 non-null    float64
 22  CBS_Autoverkopen_Totaal                 132 non-null    int64
 23  CPI_Verzekeringen_Vervoer               132 non-null    float64
 24  Jaarmutatie_CPI_Verzekeringen_Vervoer   132 non-null    float64
 25  CPI_Nieuwe_Autos                        132 non-null    float64
 26  Jaarmutatie_CPI_Nieuwe_Autos            132 non-null    float64
dtypes: float64(17), int64(8), str(2)
memory usage: 28.0 KB

Inladen CBS CPI Tweedehands Auto's dataset inladen en mergen met Bovemij dataset.

In [449]:
# Laden dataset CBS 
df_cbs_cpi_tweedehands_autos = pd.read_csv('../../data/external/CPI__prijsindex_2015_100_09032026_113401_071120_tweedehands_auto.csv', sep=';')


# Data cleaning en transformatie van de CBS dataset
# 1. Verwijder het sterretje (*) van voorlopige cijfers en spaties
df_cbs_cpi_tweedehands_autos['Perioden'] = df_cbs_cpi_tweedehands_autos['Perioden'].str.replace('*', '', regex=False).str.strip()

# 2. Splits '2021 januari' in twee losse kolommen: '2021' en 'januari'
df_cbs_cpi_tweedehands_autos[['Jaar', 'Maand_Naam']] = df_cbs_cpi_tweedehands_autos['Perioden'].str.split(' ', expand=True)

# 3. Koppel het maandnummer eraan en maak een correcte Datetime variabele (YYYY-MM-01)
df_cbs_cpi_tweedehands_autos['Maand_Num'] = df_cbs_cpi_tweedehands_autos['Maand_Naam'].map(maanden_dict)
df_cbs_cpi_tweedehands_autos['Datum'] = pd.to_datetime(df_cbs_cpi_tweedehands_autos['Jaar'] + '-' + df_cbs_cpi_tweedehands_autos['Maand_Num'] + '-01')


# Filter de data vanaf Datum 2015-01-01 en reset de index voor een correcte joining later
df_cbs_cpi_tweedehands_autos = df_cbs_cpi_tweedehands_autos[df_cbs_cpi_tweedehands_autos['Datum'] >= '2015-01-01'].reset_index(drop=True)

In [450]:
df_cbs_cpi_tweedehands_autos.head()

,Bestedingscategorieën,Perioden,CPI (2015 = 100),Jaarmutatie CPI (%),Jaar,Maand_Naam,Maand_Num,Datum
0,071120 Tweedehands auto's,2015 januari,99.16,1.8,2015,januari,01,2015-01-01
1,071120 Tweedehands auto's,2015 februari,98.98,1.5,2015,februari,02,2015-02-01
2,071120 Tweedehands auto's,2015 maart,99.81,1.6,2015,maart,03,2015-03-01
3,071120 Tweedehands auto's,2015 april,99.42,2.1,2015,april,04,2015-04-01
4,071120 Tweedehands auto's,2015 mei,99.57,2.5,2015,mei,05,2015-05-01

In [451]:
df_cbs_cpi_tweedehands_autos.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bestedingscategorieën  132 non-null    str
 1   Perioden               132 non-null    str
 2   CPI (2015 = 100)       132 non-null    float64
 3   Jaarmutatie CPI (%)    132 non-null    float64
 4   Jaar                   132 non-null    str
 5   Maand_Naam             132 non-null    str
 6   Maand_Num              132 non-null    str
 7   Datum                  132 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 8.4 KB

In [452]:
df_cbs_cpi_tweedehands_autos.describe()

       CPI (2015 = 100)  Jaarmutatie CPI (%)                       Datum
count        132.000000           132.000000                         132
mean         108.130758             2.047727  2020-06-16 02:10:54.545454
min           98.730000            -2.200000         2015-01-01 00:00:00
25%          101.037500            -0.325000         2017-09-23 12:00:00
50%          102.645000             1.100000         2020-06-16 00:00:00
75%          119.895000             2.500000         2023-03-08 18:00:00
max          122.520000            12.100000         2025-12-01 00:00:00
std            9.017128             3.484567                         NaN

In [453]:
# 1. Definieer de exacte namen die nu in je CBS dataframe staan
col_names = ['CPI (2015 = 100)', 'Jaarmutatie CPI (%)']

# 2. Selecteer deze kolommen
cbs_series = df_cbs_cpi_tweedehands_autos[col_names].copy()

# 3. Hernoem de kolommen handmatig naar namen met underscores
cbs_series.columns = ['CPI_Tweedehands_Autos', 'Jaarmutatie_CPI_Tweedehands_Autos']

# 4. Voeg ze samen met de Bovemij data
df_merged_4 = df_merged_3.join(cbs_series, how='inner')
df_merged_4.index.freq = 'MS'

In [454]:
df_merged_4.head()

,Jaar_Maand,Product,Label_Naam,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,...,Jaarpremie_Prolongatie,Gemiddelde_Jaarpremie_voor_Prolongatie,Gemiddelde_Jaarpremie_na_Prolongatie,CBS_Autoverkopen_Totaal,CPI_Verzekeringen_Vervoer,Jaarmutatie_CPI_Verzekeringen_Vervoer,CPI_Nieuwe_Autos,Jaarmutatie_CPI_Nieuwe_Autos,CPI_Tweedehands_Autos,Jaarmutatie_CPI_Tweedehands_Autos
0,201507,Auto Particulier,BCS Polis,50,29585.43,106,59337.54,56,28886.31,0,...,0.0,0.0,0.0,284629,99.66,3.8,100.16,2.7,99.16,1.8
1,201508,Auto Particulier,BCS Polis,106,59337.54,168,91685.32,65,32911.85,1,...,0.0,0.0,0.0,243121,99.68,3.9,100.03,2.4,98.98,1.5
2,201509,Auto Particulier,BCS Polis,168,91685.32,216,111434.76,54,23342.33,6,...,0.0,0.0,0.0,257217,99.76,3.9,100.05,2.7,99.81,1.6
3,201510,Auto Particulier,BCS Polis,216,111434.76,265,133615.83,57,26433.61,6,...,0.0,0.0,0.0,247228,99.79,3.8,99.63,2.6,99.42,2.1
4,201511,Auto Particulier,BCS Polis,265,133615.83,309,157925.46,49,26034.01,5,...,0.0,0.0,0.0,244140,99.79,3.7,99.52,2.5,99.57,2.5

In [455]:
df_merged_4.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 29 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Jaar_Maand                              132 non-null    int64
 1   Product                                 132 non-null    str
 2   Label_Naam                              132 non-null    str
 3   Beginstand                              132 non-null    int64
 4   Jaarpremie_Beginstand                   132 non-null    float64
 5   Eindstand                               132 non-null    int64
 6   Jaarpremie_Eindstand                    132 non-null    float64
 7   NewBusiness                             132 non-null    int64
 8   Jaarpremie_NewBusiness                  132 non-null    float64
 9   Royementen                              132 non-null    int64
 10  Geroyeerde_Jaarpremie                   132 non-null    float64
 11  Prolongaties                            132 non-null    int64
 12  Jaarpremie_voor_Prolongatie             132 non-null    float64
 13  Jaarpremie_na_Prolongatie               132 non-null    float64
 14  Mutaties                                132 non-null    int64
 15  Jaarpremie_voor_Mutatie                 132 non-null    float64
 16  Jaarpremie_na_Mutatie                   132 non-null    float64
 17  Gemiddelde_Jaarpremie_Beginstand        132 non-null    float64
 18  Gemiddelde_Jaarpremie_Eindstand         132 non-null    float64
 19  Jaarpremie_Prolongatie                  132 non-null    float64
 20  Gemiddelde_Jaarpremie_voor_Prolongatie  132 non-null    float64
 21  Gemiddelde_Jaarpremie_na_Prolongatie    132 non-null    float64
 22  CBS_Autoverkopen_Totaal                 132 non-null    int64
 23  CPI_Verzekeringen_Vervoer               132 non-null    float64
 24  Jaarmutatie_CPI_Verzekeringen_Vervoer   132 non-null    float64
 25  CPI_Nieuwe_Autos                        132 non-null    float64
 26  Jaarmutatie_CPI_Nieuwe_Autos            132 non-null    float64
 27  CPI_Tweedehands_Autos                   132 non-null    float64
 28  Jaarmutatie_CPI_Tweedehands_Autos       132 non-null    float64
dtypes: float64(19), int64(8), str(2)
memory usage: 30.0 KB

Inladen CBS CPI Onderhoud en Reparatie Privevoertuigen dataset inladen en mergen met Bovemij dataset.

In [456]:
# Laden dataset CBS 
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen = pd.read_csv('../../data/external/CPI__prijsindex_2015_100_09032026_104746_072300_onderhoud_en_reparatie_privevoertuigen.csv', sep=';')


# Data cleaning en transformatie van de CBS dataset
# 1. Verwijder het sterretje (*) van voorlopige cijfers en spaties
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Perioden'] = df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Perioden'].str.replace('*', '', regex=False).str.strip()

# 2. Splits '2021 januari' in twee losse kolommen: '2021' en 'januari'
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen[['Jaar', 'Maand_Naam']] = df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Perioden'].str.split(' ', expand=True)

# 3. Koppel het maandnummer eraan en maak een correcte Datetime variabele (YYYY-MM-01)
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Maand_Num'] = df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Maand_Naam'].map(maanden_dict)
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Datum'] = pd.to_datetime(df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Jaar'] + '-' + df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Maand_Num'] + '-01')


# Filter de data vanaf Datum 2015-01-01 en reset de index voor een correcte joining later
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen = df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen[df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen['Datum'] >= '2015-01-01'].reset_index(drop=True)

In [457]:
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen.head()

,Bestedingscategorieën,Perioden,CPI (2015 = 100),Jaarmutatie CPI (%),Jaar,Maand_Naam,Maand_Num,Datum
0,072300 Onderhoud en rep. privévoertuigen,2015 januari,100.08,0.7,2015,januari,01,2015-01-01
1,072300 Onderhoud en rep. privévoertuigen,2015 februari,98.66,-0.6,2015,februari,02,2015-02-01
2,072300 Onderhoud en rep. privévoertuigen,2015 maart,99.59,0.3,2015,maart,03,2015-03-01
3,072300 Onderhoud en rep. privévoertuigen,2015 april,99.90,0.9,2015,april,04,2015-04-01
4,072300 Onderhoud en rep. privévoertuigen,2015 mei,99.85,0.9,2015,mei,05,2015-05-01

In [458]:
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bestedingscategorieën  132 non-null    str
 1   Perioden               132 non-null    str
 2   CPI (2015 = 100)       132 non-null    float64
 3   Jaarmutatie CPI (%)    132 non-null    float64
 4   Jaar                   132 non-null    str
 5   Maand_Naam             132 non-null    str
 6   Maand_Num              132 non-null    str
 7   Datum                  132 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 8.4 KB

In [459]:
df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen.describe()

       CPI (2015 = 100)  Jaarmutatie CPI (%)                       Datum
count        132.000000           132.000000                         132
mean         115.297727             3.490152  2020-06-16 02:10:54.545454
min           98.550000            -5.200000         2015-01-01 00:00:00
25%          102.472500             1.300000         2017-09-23 12:00:00
50%          109.765000             3.350000         2020-06-16 00:00:00
75%          128.117500             5.525000         2023-03-08 18:00:00
max          148.300000             9.800000         2025-12-01 00:00:00
std           14.789642             3.057536                         NaN

In [460]:
# 1. Definieer de exacte namen die nu in je CBS dataframe staan
col_names = ['CPI (2015 = 100)', 'Jaarmutatie CPI (%)']

# 2. Selecteer deze kolommen
cbs_series = df_cbs_cpi_onderhoud_en_reparatie_privevoertuigen[col_names].copy()

# 3. Hernoem de kolommen handmatig naar namen met underscores
cbs_series.columns = ['CPI_Onderhoud_en_Reparatie_Privevoertuigen', 'Jaarmutatie_CPI_Onderhoud_en_Reparatie_Privevoertuigen']

# 4. Voeg ze samen met de Bovemij data
df_merged_5 = df_merged_4.join(cbs_series, how='inner')
df_merged_5.index.freq = 'MS'

In [461]:
df_merged_5.head()

,Jaar_Maand,Product,Label_Naam,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,...,Gemiddelde_Jaarpremie_na_Prolongatie,CBS_Autoverkopen_Totaal,CPI_Verzekeringen_Vervoer,Jaarmutatie_CPI_Verzekeringen_Vervoer,CPI_Nieuwe_Autos,Jaarmutatie_CPI_Nieuwe_Autos,CPI_Tweedehands_Autos,Jaarmutatie_CPI_Tweedehands_Autos,CPI_Onderhoud_en_Reparatie_Privevoertuigen,Jaarmutatie_CPI_Onderhoud_en_Reparatie_Privevoertuigen
0,201507,Auto Particulier,BCS Polis,50,29585.43,106,59337.54,56,28886.31,0,...,0.0,284629,99.66,3.8,100.16,2.7,99.16,1.8,100.08,0.7
1,201508,Auto Particulier,BCS Polis,106,59337.54,168,91685.32,65,32911.85,1,...,0.0,243121,99.68,3.9,100.03,2.4,98.98,1.5,98.66,-0.6
2,201509,Auto Particulier,BCS Polis,168,91685.32,216,111434.76,54,23342.33,6,...,0.0,257217,99.76,3.9,100.05,2.7,99.81,1.6,99.59,0.3
3,201510,Auto Particulier,BCS Polis,216,111434.76,265,133615.83,57,26433.61,6,...,0.0,247228,99.79,3.8,99.63,2.6,99.42,2.1,99.90,0.9
4,201511,Auto Particulier,BCS Polis,265,133615.83,309,157925.46,49,26034.01,5,...,0.0,244140,99.79,3.7,99.52,2.5,99.57,2.5,99.85,0.9

In [462]:
df_merged_5.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 31 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Jaar_Maand                                              132 non-null    int64
 1   Product                                                 132 non-null    str
 2   Label_Naam                                              132 non-null    str
 3   Beginstand                                              132 non-null    int64
 4   Jaarpremie_Beginstand                                   132 non-null    float64
 5   Eindstand                                               132 non-null    int64
 6   Jaarpremie_Eindstand                                    132 non-null    float64
 7   NewBusiness                                             132 non-null    int64
 8   Jaarpremie_NewBusiness                                  132 non-null    float64
 9   Royementen                                              132 non-null    int64
 10  Geroyeerde_Jaarpremie                                   132 non-null    float64
 11  Prolongaties                                            132 non-null    int64
 12  Jaarpremie_voor_Prolongatie                             132 non-null    float64
 13  Jaarpremie_na_Prolongatie                               132 non-null    float64
 14  Mutaties                                                132 non-null    int64
 15  Jaarpremie_voor_Mutatie                                 132 non-null    float64
 16  Jaarpremie_na_Mutatie                                   132 non-null    float64
 17  Gemiddelde_Jaarpremie_Beginstand                        132 non-null    float64
 18  Gemiddelde_Jaarpremie_Eindstand                         132 non-null    float64
 19  Jaarpremie_Prolongatie                                  132 non-null    float64
 20  Gemiddelde_Jaarpremie_voor_Prolongatie                  132 non-null    float64
 21  Gemiddelde_Jaarpremie_na_Prolongatie                    132 non-null    float64
 22  CBS_Autoverkopen_Totaal                                 132 non-null    int64
 23  CPI_Verzekeringen_Vervoer                               132 non-null    float64
 24  Jaarmutatie_CPI_Verzekeringen_Vervoer                   132 non-null    float64
 25  CPI_Nieuwe_Autos                                        132 non-null    float64
 26  Jaarmutatie_CPI_Nieuwe_Autos                            132 non-null    float64
 27  CPI_Tweedehands_Autos                                   132 non-null    float64
 28  Jaarmutatie_CPI_Tweedehands_Autos                       132 non-null    float64
 29  CPI_Onderhoud_en_Reparatie_Privevoertuigen              132 non-null    float64
 30  Jaarmutatie_CPI_Onderhoud_en_Reparatie_Privevoertuigen  132 non-null    float64
dtypes: float64(21), int64(8), str(2)
memory usage: 32.1 KB

Inladen CBS CPI Brandstoffen en Smeermiddelen dataset inladen en mergen met Bovemij dataset.

In [463]:
# Laden dataset CBS 
df_cbs_cpi_brandstoffen = pd.read_csv('../../data/external/CPI__prijsindex_2015_100_09032026_105008_072200_brandstoffen_en_smeermiddelen.csv', sep=';')


# Data cleaning en transformatie van de CBS dataset
# 1. Verwijder het sterretje (*) van voorlopige cijfers en spaties
df_cbs_cpi_brandstoffen['Perioden'] = df_cbs_cpi_brandstoffen['Perioden'].str.replace('*', '', regex=False).str.strip()

# 2. Splits '2021 januari' in twee losse kolommen: '2021' en 'januari'
df_cbs_cpi_brandstoffen[['Jaar', 'Maand_Naam']] = df_cbs_cpi_brandstoffen['Perioden'].str.split(' ', expand=True)

# 3. Koppel het maandnummer eraan en maak een correcte Datetime variabele (YYYY-MM-01)
df_cbs_cpi_brandstoffen['Maand_Num'] = df_cbs_cpi_brandstoffen['Maand_Naam'].map(maanden_dict)
df_cbs_cpi_brandstoffen['Datum'] = pd.to_datetime(df_cbs_cpi_brandstoffen['Jaar'] + '-' + df_cbs_cpi_brandstoffen['Maand_Num'] + '-01')


# Filter de data vanaf Datum 2015-01-01 en reset de index voor een correcte joining later
df_cbs_cpi_brandstoffen = df_cbs_cpi_brandstoffen[df_cbs_cpi_brandstoffen['Datum'] >= '2015-01-01'].reset_index(drop=True)

In [464]:
df_cbs_cpi_brandstoffen.head()

,Bestedingscategorieën,Perioden,CPI (2015 = 100),Jaarmutatie CPI (%),Jaar,Maand_Naam,Maand_Num,Datum
0,072200 Brandstoffen en smeermiddelen,2015 januari,95.24,-13.7,2015,januari,01,2015-01-01
1,072200 Brandstoffen en smeermiddelen,2015 februari,98.65,-10.8,2015,februari,02,2015-02-01
2,072200 Brandstoffen en smeermiddelen,2015 maart,102.62,-6.6,2015,maart,03,2015-03-01
3,072200 Brandstoffen en smeermiddelen,2015 april,103.91,-7.1,2015,april,04,2015-04-01
4,072200 Brandstoffen en smeermiddelen,2015 mei,105.58,-5.9,2015,mei,05,2015-05-01

In [465]:
df_cbs_cpi_brandstoffen.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bestedingscategorieën  132 non-null    str
 1   Perioden               132 non-null    str
 2   CPI (2015 = 100)       132 non-null    float64
 3   Jaarmutatie CPI (%)    132 non-null    float64
 4   Jaar                   132 non-null    str
 5   Maand_Naam             132 non-null    str
 6   Maand_Num              132 non-null    str
 7   Datum                  132 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 8.4 KB

In [466]:
df_cbs_cpi_brandstoffen.describe()

       CPI (2015 = 100)  Jaarmutatie CPI (%)                       Datum
count        132.000000           132.000000                         132
mean         114.101439             2.099242  2020-06-16 02:10:54.545454
min           88.610000           -23.200000         2015-01-01 00:00:00
25%          100.405000            -6.800000         2017-09-23 12:00:00
50%          108.580000             0.600000         2020-06-16 00:00:00
75%          128.547500             9.175000         2023-03-08 18:00:00
max          157.170000            36.500000         2025-12-01 00:00:00
std           16.015904            11.624261                         NaN

In [ ]:
# 1. Definieer de exacte namen die nu in je CBS dataframe staan
col_names = ['CPI (2015 = 100)', 'Jaarmutatie CPI (%)']

# 2. Selecteer deze kolommen
cbs_series = df_cbs_cpi_brandstoffen[col_names].copy()

# 3. Hernoem de kolommen handmatig naar namen met underscores
cbs_series.columns = ['CPI_Brandstoffen', 'Jaarmutatie_CPI_Brandstoffen']

# 4. Voeg ze samen met de Bovemij data
df_merged_6 = df_merged_5.join(cbs_series, how='left')
df_merged_6.index.freq = 'MS'

In [468]:
df_merged_6.head()

,Jaar_Maand,Product,Label_Naam,Beginstand,Jaarpremie_Beginstand,Eindstand,Jaarpremie_Eindstand,NewBusiness,Jaarpremie_NewBusiness,Royementen,...,CPI_Verzekeringen_Vervoer,Jaarmutatie_CPI_Verzekeringen_Vervoer,CPI_Nieuwe_Autos,Jaarmutatie_CPI_Nieuwe_Autos,CPI_Tweedehands_Autos,Jaarmutatie_CPI_Tweedehands_Autos,CPI_Onderhoud_en_Reparatie_Privevoertuigen,Jaarmutatie_CPI_Onderhoud_en_Reparatie_Privevoertuigen,CPI_Brandstoffen,Jaarmutatie_CPI_Brandstoffen
0,201507,Auto Particulier,BCS Polis,50,29585.43,106,59337.54,56,28886.31,0,...,99.66,3.8,100.16,2.7,99.16,1.8,100.08,0.7,95.24,-13.7
1,201508,Auto Particulier,BCS Polis,106,59337.54,168,91685.32,65,32911.85,1,...,99.68,3.9,100.03,2.4,98.98,1.5,98.66,-0.6,98.65,-10.8
2,201509,Auto Particulier,BCS Polis,168,91685.32,216,111434.76,54,23342.33,6,...,99.76,3.9,100.05,2.7,99.81,1.6,99.59,0.3,102.62,-6.6
3,201510,Auto Particulier,BCS Polis,216,111434.76,265,133615.83,57,26433.61,6,...,99.79,3.8,99.63,2.6,99.42,2.1,99.90,0.9,103.91,-7.1
4,201511,Auto Particulier,BCS Polis,265,133615.83,309,157925.46,49,26034.01,5,...,99.79,3.7,99.52,2.5,99.57,2.5,99.85,0.9,105.58,-5.9

In [469]:
df_merged_6.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 33 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Jaar_Maand                                              132 non-null    int64
 1   Product                                                 132 non-null    str
 2   Label_Naam                                              132 non-null    str
 3   Beginstand                                              132 non-null    int64
 4   Jaarpremie_Beginstand                                   132 non-null    float64
 5   Eindstand                                               132 non-null    int64
 6   Jaarpremie_Eindstand                                    132 non-null    float64
 7   NewBusiness                                             132 non-null    int64
 8   Jaarpremie_NewBusiness                                  132 non-null    float64
 9   Royementen                                              132 non-null    int64
 10  Geroyeerde_Jaarpremie                                   132 non-null    float64
 11  Prolongaties                                            132 non-null    int64
 12  Jaarpremie_voor_Prolongatie                             132 non-null    float64
 13  Jaarpremie_na_Prolongatie                               132 non-null    float64
 14  Mutaties                                                132 non-null    int64
 15  Jaarpremie_voor_Mutatie                                 132 non-null    float64
 16  Jaarpremie_na_Mutatie                                   132 non-null    float64
 17  Gemiddelde_Jaarpremie_Beginstand                        132 non-null    float64
 18  Gemiddelde_Jaarpremie_Eindstand                         132 non-null    float64
 19  Jaarpremie_Prolongatie                                  132 non-null    float64
 20  Gemiddelde_Jaarpremie_voor_Prolongatie                  132 non-null    float64
 21  Gemiddelde_Jaarpremie_na_Prolongatie                    132 non-null    float64
 22  CBS_Autoverkopen_Totaal                                 132 non-null    int64
 23  CPI_Verzekeringen_Vervoer                               132 non-null    float64
 24  Jaarmutatie_CPI_Verzekeringen_Vervoer                   132 non-null    float64
 25  CPI_Nieuwe_Autos                                        132 non-null    float64
 26  Jaarmutatie_CPI_Nieuwe_Autos                            132 non-null    float64
 27  CPI_Tweedehands_Autos                                   132 non-null    float64
 28  Jaarmutatie_CPI_Tweedehands_Autos                       132 non-null    float64
 29  CPI_Onderhoud_en_Reparatie_Privevoertuigen              132 non-null    float64
 30  Jaarmutatie_CPI_Onderhoud_en_Reparatie_Privevoertuigen  132 non-null    float64
 31  CPI_Brandstoffen                                        132 non-null    float64
 32  Jaarmutatie_CPI_Brandstoffen                            132 non-null    float64
dtypes: float64(23), int64(8), str(2)
memory usage: 34.2 KB

In [ ]:
#Exporteer naar CSV
# index=True is hier belangrijk omdat we 'Datum' als index hebben gezet
df_merged_6.to_csv('../../data/processed/export_insurance_portfolio_data_forecasting_2015_2025_enriched.csv', index=True)

print("Bestand succesvol opgeslagen als 'export_insurance_portfolio_data_forecasting_2015_2025_enriched.csv'")
print(f"Aantal maanden in dataset: {len(df_merged_6)}")